CREATE TABLE IF NOT EXISTS clients (
    sno INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL,
    email VARCHAR(50),
    Reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
     );